In [1]:
pwd

'C:\\Users\\Henry\\Desktop\\my Portfolio\\DEEP_LEARNING_LOGISTICS'

In [2]:
import numpy as np
from numpy.random import seed 
seed(1) 
import pandas as pd
import tensorflow as tf
!pip install keras
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
tf.random.set_seed(1234)
from keras.utils import to_categorical
from sklearn.metrics import classification_report



In [3]:
data = pd.read_csv('etete.csv')

In [4]:
data.head(2)

Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0    1.005844    0.412816   -0.536062   -0.806331    0.767431    0.880469   
1   -1.574681   -1.141882    2.130803   -0.806331    1.002633   -0.019280   

   Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0    0.268487   -1.556984         0.0         0.0          0.0          1.0   
1   -0.589690   -1.556984         0.0         0.0          0.0          0.0   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  
0          1.0          0.0            1  
1          1.0          0.0            0

In [5]:
data.shape

(607, 15)

In [6]:
data.columns = ['']*len(data.columns)
data.index = ['']*len(data.index)

In [7]:
data.head(2)

\
  1.005844  0.412816 -0.536062 -0.806331  0.767431  0.880469  0.268487   
 -1.574681 -1.141882  2.130803 -0.806331  1.002633 -0.019280 -0.589690   

                                             
 -1.556984  0.0  0.0  0.0  1.0  1.0  0.0  1  
 -1.556984  0.0  0.0  0.0  0.0  1.0  0.0  0

In [8]:
new_data = data.copy()

In [9]:
data_1=new_data.iloc[:,-1]

In [10]:
data_2 =new_data.iloc[:,:-1]

In [11]:
data_1.head(5)

    1
    0
    0
    1
    0
Name: , dtype: int64

In [12]:
y_cat = to_categorical(data_1)

In [13]:
y_cat

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [14]:
data_2.shape

(607, 14)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_2, y_cat , test_size=0.3, random_state=7)

In [16]:

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((424, 14), (183, 14), (424, 2), (183, 2))

In [17]:
# MODELING FOR 8 FEATURES
# build the model using Keras approach

input_size = 14   # number of features
output_size =2    
hidden_layer_size =100  
Early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)

In [18]:
from keras.models import Sequential
# Import `Dense` from `keras.layers`
from keras.layers import Dense
# Initialize the constructor
model = Sequential()
# Add an input layer 
model.add(Dense(12, activation='relu', input_shape=(14,)))
# Add one hidden layer 
model.add(Dense(8, activation='relu'))
model.add(Dense(8, activation='relu'))
# Add an output layer 
model.add(Dense(2, activation='sigmoid'))

In [19]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
                   
model.fit(
X_train, y_train,epochs=20, batch_size=9,callbacks=[Early_stopping],validation_split=0.1, verbose=2)

Epoch 1/20
43/43 - 1s - loss: 0.7100 - accuracy: 0.5354 - val_loss: 0.6990 - val_accuracy: 0.5349
Epoch 2/20
43/43 - 0s - loss: 0.6916 - accuracy: 0.5459 - val_loss: 0.6922 - val_accuracy: 0.5349
Epoch 3/20
43/43 - 0s - loss: 0.6790 - accuracy: 0.5801 - val_loss: 0.6906 - val_accuracy: 0.4884
Epoch 4/20
43/43 - 0s - loss: 0.6700 - accuracy: 0.6037 - val_loss: 0.6941 - val_accuracy: 0.5116
Epoch 5/20
43/43 - 0s - loss: 0.6592 - accuracy: 0.6352 - val_loss: 0.6953 - val_accuracy: 0.5581


In [20]:
score = model.evaluate(X_train,y_train,verbose=1)
print(score)

14/14 [==============================] - 0s 537us/step - loss: 0.6560 - accuracy: 0.6321
[0.655954897403717, 0.6320754885673523]


In [21]:
y_pred = model.predict( X_test)

In [22]:
score = model.evaluate(X_test, y_test,verbose=1)

print(score)

6/6 [==============================] - 0s 598us/step - loss: 0.6809 - accuracy: 0.6011
[0.680925726890564, 0.6010928750038147]


In [23]:
y_pred.shape

(183, 2)

In [24]:
y_test[:5],  y_pred[:5]

(array([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.]], dtype=float32),
 array([[0.619102  , 0.35924843],
        [0.5413627 , 0.39673418],
        [0.47119153, 0.52040863],
        [0.67122996, 0.28701067],
        [0.5430644 , 0.47836086]], dtype=float32))

In [25]:
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1) 

In [26]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test_class ,y_pred_class)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 60.11%
